apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml
  - secret.yaml

# Common labels to be applied to all resources
commonLabels:
  app: dekallm-benchmark-ui
  environment: production

# Configuration for pods
replicas:
  - name: dekallm-benchmark-ui
    count: 2

# Namespace where resources will be created
namespace: dekallm-benchmark